Repository openshift/federation-v2-operator, pull requests merged in 2019-04, with the labels that each got.

#66 Fix bug in push-operator-registry script
  scripts/push-operator-registry.sh
Labels: approved, size/XS

#70 [CSV] Fix federation 0.0.8 manifest for OLM
  manifests/federation/0.0.8/federation.v0.0.8.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#71 Update dangling references to 0.0.7
  manifests/cluster-federation/0.0.8/cluster-federation.v0.0.8.clusterserviceversion.yaml
  upstream-manifests/cluster-federation/0.0.8/cluster-federation.v0.0.8.clusterserviceversion.yaml
  upstream-manifests/federation/0.0.8/federation.v0.0.8.clusterserviceversion.yaml
Labels: approved, size/S

#72 Update README with information about OperatorHub
  README.md
Labels: approved, size/M

#75 Delete manifests directory
  README.md
  manifests/cluster-federation/0.0.8/cluster-federation-core-ClusterPropagatedVersion.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation-core-DNSEndpoint.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation-core-Domain.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation-core-FederatedCluster.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation-core-FederatedServiceStatus.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation-core-FederatedTypeConfig.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation-core-FederationConfig.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation-core-IngressDNSRecord.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation-core-PropagatedVersion.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation-core-ReplicaSchedulingPreference.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation-core-ServiceDNSRecord.crd.yaml
  manifests/cluster-federation/0.0.8/cluster-federation.v0.0.8.clusterserviceversion.yaml
  manifests/cluster-federation/0.0.8/cluster-registry.crd.yaml
  manifests/cluster-federation/cluster-federation.package.yaml
  manifests/federation/0.0.8/cluster-registry.crd.yaml
  manifests/federation/0.0.8/federation-core-ClusterPropagatedVersion.crd.yaml
  manifests/federation/0.0.8/federation-core-DNSEndpoint.crd.yaml
  manifests/federation/0.0.8/federation-core-Domain.crd.yaml
  manifests/federation/0.0.8/federation-core-FederatedCluster.crd.yaml
  manifests/federation/0.0.8/federation-core-FederatedServiceStatus.crd.yaml
  manifests/federation/0.0.8/federation-core-FederatedTypeConfig.crd.yaml
  manifests/federation/0.0.8/federation-core-FederationConfig.crd.yaml
  manifests/federation/0.0.8/federation-core-IngressDNSRecord.crd.yaml
  manifests/federation/0.0.8/federation-core-PropagatedVersion.crd.yaml
  manifests/federation/0.0.8/federation-core-ReplicaSchedulingPreference.crd.yaml
  manifests/federation/0.0.8/federation-core-ServiceDNSRecord.crd.yaml
  manifests/federation/0.0.8/federation.v0.0.8.clusterserviceversion.yaml
  manifests/federation/federation.package.yaml
  olm-testing/Dockerfile
  scripts/populate-olm-crds.sh
  scripts/push-operator-registry.sh
Labels: approved, size/XXL
