Repository openshift/federation-v2-operator, pull requests merged in 2019-03, with the labels that each got.

#42 Fix registry push script
  olm-testing/Dockerfile
Labels: approved, size/XS

#43 Minor updates to readme / fix federation reported version
  Dockerfile
  README.md
Labels: approved, size/S

#39 Add required annotations to CSV
  manifests/federation/0.0.5/federation.v0.0.5.clusterserviceversion.yaml
Labels: approved, size/S

#46 Script cleanup + introduce makefile for ci
  Makefile.ci
  scripts/populate-federation-gopath.sh
Labels: approved, size/M

#50 Fix entrypoint in federation-controller image
  Dockerfile
Labels: approved, size/XS

#52 Remove dependency on oc binary
  scripts/install-using-catalog-source.sh
Labels: approved, size/XS

#53 Community operators tooling
  manifests/federation/0.0.6/federation.v0.0.6.clusterserviceversion.yaml
  scripts/populate-community-operators.sh
Labels: approved, size/L

#54 Fix typo in OLM link
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#62 Updated instructions for getting kubefed2 from GH releases
  manifests/federation/0.0.7/federation.v0.0.7.clusterserviceversion.yaml
  upstream-manifests/federation/0.0.7/federation.v0.0.7.clusterserviceversion.yaml
Labels: size/S

#61 Update README with info about upstream-manifests
  README.md
Labels: approved, size/S

#63 Minor CSV/tooling updates
  scripts/populate-community-operators.sh
  upstream-manifests/federation/0.0.7/federation.v0.0.7.clusterserviceversion.yaml
Labels: approved, size/S

#64 Add repository/link information to metadata
  upstream-manifests/federation/0.0.7/federation.v0.0.7.clusterserviceversion.yaml
Labels: approved, size/XS
